site_name: AGS Tween Module
repo_url: https://github.com/edmundito/ags-tween
pages:
  - ['getting-started.md', 'Getting Started']
  - ['scripting/enums.md', 'Basic', 'Enumerated Types']
  - ['scripting/generaltweens.md', 'Basic', 'General Tweens']
  - ['scripting/guicontroltweens.md', 'Basic', 'GUI Control Specific Tweens']
  - ['scripting/systemtweens.md', 'Basic', 'System Specific Tweens']
  - ['scripting/audiotweens.md', 'Basic', 'Audio Specific Tweens']
  - ['scripting/globaltween.md', 'Basic', 'Global Tween Functions']
  - ['scripting/settings.md', 'Advanced', 'Settings']
  - ['scripting/tween.md', 'Advanced', 'Custom Tweens']
  - ['scripting/globaltiming.md', 'Bonus', 'Timing Utilities']
  - ['scripting/tweengame.md', 'Bonus', 'TweenGame Utilities']
  - ['scripting/tweenmaths.md', 'Bonus', 'TweenMaths Utilities']
  - ['scripting/tweeneasing.md', 'Bonus', 'TweenEasing Equations']
